# @author kirin-dev
# @date 2022/6/20
# @version 1.0

# introduce cayman
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

# web information 
title: '闲人'
description: 'in the bleak midwinter'
show_downloads: false
google_analytics: 'https://github.com/kirin-dev/kirin-dev.github.io/'
